name: "Letta Code Action"
description: "Stateful AI coding agent for GitHub. Tag @letta-code in issues/PRs to get help with code review, bug fixes, and feature implementation. Agents persist across conversations."
branding:
  icon: "cpu"
  color: "purple"

inputs:
  trigger_phrase:
    description: "The trigger phrase to look for in comments or issue body"
    required: false
    default: "@letta-code"
  assignee_trigger:
    description: "The assignee username that triggers the action (e.g. @letta-code)"
    required: false
  label_trigger:
    description: "The label that triggers the action (e.g. letta)"
    required: false
    default: "letta-code"
  base_branch:
    description: "The branch to use as the base/source when creating new branches (defaults to repository default branch)"
    required: false
  branch_prefix:
    description: "The prefix to use for Letta branches (defaults to 'letta/', use 'letta-' for dash format)"
    required: false
    default: "letta/"
  allowed_bots:
    description: "Comma-separated list of allowed bot usernames, or '*' to allow all bots. Empty string (default) allows no bots."
    required: false
    default: ""
  allowed_non_write_users:
    description: "Comma-separated list of usernames to allow without write permissions, or '*' to allow all users. Only works when github_token input is provided. WARNING: Use with extreme caution - this bypasses security checks and should only be used for workflows with very limited permissions (e.g., issue labeling)."
    required: false
    default: ""

  # Letta Code configuration
  prompt:
    description: "Instructions for Letta. Can be a direct prompt or custom template."
    required: false
    default: ""

  # Auth configuration
  letta_api_key:
    description: "Letta API key (get one at https://app.letta.com)"
    required: false
  letta_base_url:
    description: "Letta API base URL (defaults to https://api.letta.com)"
    required: false
    default: ""
  github_token:
    description: "GitHub token with repo and pull request permissions. Use GITHUB_TOKEN or a token from actions/create-github-app-token for custom bot identity."
    required: true

  letta_args:
    description: "Additional arguments to pass directly to Letta CLI"
    required: false
    default: ""
  additional_permissions:
    description: "Additional GitHub permissions to request (e.g., 'actions: read')"
    required: false
    default: ""
  use_sticky_comment:
    description: "Use just one comment to deliver issue/PR comments"
    required: false
    default: "false"
  use_commit_signing:
    description: "Enable commit signing using GitHub's commit signature verification. When false, Letta uses standard git commands"
    required: false
    default: "false"
  bot_id:
    description: "GitHub user ID to use for git operations (defaults to letta-code)"
    required: false
    default: "248085862"
  bot_name:
    description: "GitHub username to use for git operations"
    required: false
    default: "letta-code"
  track_progress:
    description: "Force tag mode with tracking comments for pull_request and issue events. Only applicable to pull_request (opened, synchronize, ready_for_review, reopened) and issue (opened, edited, labeled, assigned) events."
    required: false
    default: "false"
  path_to_letta_executable:
    description: "Optional path to a custom Letta Code executable. If provided, skips automatic installation and uses this executable instead."
    required: false
    default: ""
  path_to_bun_executable:
    description: "Optional path to a custom Bun executable. If provided, skips automatic Bun installation and uses this executable instead. WARNING: Using an incompatible version may cause problems if the action requires specific Bun features. This input is typically not needed unless you're debugging something specific or have unique needs in your environment."
    required: false
    default: ""
  show_full_output:
    description: "Show full JSON output from Letta Code. WARNING: This outputs ALL Letta messages including tool execution results which may contain secrets. Only enable for debugging."
    required: false
    default: "false"
  model:
    description: "Model to use for the Letta agent (e.g., opus, sonnet-4.5, haiku, gpt-4.1)"
    required: false
    default: "opus"

outputs:
  execution_file:
    description: "Path to the Letta Code execution output file"
    value: ${{ steps.letta-code.outputs.execution_file }}
  agent_id:
    description: "The Letta agent ID used for this execution"
    value: ${{ steps.letta-code.outputs.agent_id }}
  branch_name:
    description: "The branch created by Letta Code for this execution"
    value: ${{ steps.prepare.outputs.LETTA_BRANCH }}
  github_token:
    description: "The GitHub token used by the action"
    value: ${{ steps.prepare.outputs.github_token }}

runs:
  using: "composite"
  steps:
    - name: Install Bun
      if: inputs.path_to_bun_executable == ''
      uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # https://github.com/oven-sh/setup-bun/releases/tag/v2.0.2
      with:
        bun-version: 1.2.11

    - name: Setup Custom Bun Path
      if: inputs.path_to_bun_executable != ''
      shell: bash
      run: |
        echo "Using custom Bun executable: ${{ inputs.path_to_bun_executable }}"
        # Add the directory containing the custom executable to PATH
        BUN_DIR=$(dirname "${{ inputs.path_to_bun_executable }}")
        echo "$BUN_DIR" >> "$GITHUB_PATH"

    - name: Install Dependencies
      shell: bash
      run: |
        cd ${GITHUB_ACTION_PATH}
        bun install

    - name: Prepare action
      id: prepare
      shell: bash
      run: |
        bun run ${GITHUB_ACTION_PATH}/src/entrypoints/prepare.ts
      env:
        MODE: ${{ inputs.mode }}
        PROMPT: ${{ inputs.prompt }}
        TRIGGER_PHRASE: ${{ inputs.trigger_phrase }}
        ASSIGNEE_TRIGGER: ${{ inputs.assignee_trigger }}
        LABEL_TRIGGER: ${{ inputs.label_trigger }}
        BASE_BRANCH: ${{ inputs.base_branch }}
        BRANCH_PREFIX: ${{ inputs.branch_prefix }}
        OVERRIDE_GITHUB_TOKEN: ${{ inputs.github_token }}
        ALLOWED_BOTS: ${{ inputs.allowed_bots }}
        ALLOWED_NON_WRITE_USERS: ${{ inputs.allowed_non_write_users }}
        GITHUB_RUN_ID: ${{ github.run_id }}
        USE_STICKY_COMMENT: ${{ inputs.use_sticky_comment }}
        DEFAULT_WORKFLOW_TOKEN: ${{ github.token }}
        USE_COMMIT_SIGNING: ${{ inputs.use_commit_signing }}
        BOT_ID: ${{ inputs.bot_id }}
        BOT_NAME: ${{ inputs.bot_name }}
        TRACK_PROGRESS: ${{ inputs.track_progress }}
        ADDITIONAL_PERMISSIONS: ${{ inputs.additional_permissions }}
        LETTA_ARGS: ${{ inputs.letta_args }}
        ALL_INPUTS: ${{ toJson(inputs) }}

    - name: Install Base Action Dependencies
      if: steps.prepare.outputs.contains_trigger == 'true'
      shell: bash
      run: |
        echo "Dependencies already installed"

        # Install Letta Code if no custom executable is provided
        if [ -z "${{ inputs.path_to_letta_executable }}" ]; then
          echo "Installing Letta Code..."
          npm install -g @letta-ai/letta-code
          echo "Letta Code installed successfully"
        else
          echo "Using custom Letta Code executable: ${{ inputs.path_to_letta_executable }}"
          LETTA_DIR=$(dirname "${{ inputs.path_to_letta_executable }}")
          echo "$LETTA_DIR" >> "$GITHUB_PATH"
        fi

    - name: Setup GitHub Action Skill
      if: steps.prepare.outputs.contains_trigger == 'true'
      shell: bash
      run: |
        echo "Setting up GitHub Action skill..."
        mkdir -p .skills/github-action
        cp ${GITHUB_ACTION_PATH}/skills/github-action/SKILL.md .skills/github-action/
        echo "GitHub Action skill installed"

    - name: Run Letta Code
      id: letta-code
      if: steps.prepare.outputs.contains_trigger == 'true'
      shell: bash
      run: |
        # Run the Letta runner
        bun run ${GITHUB_ACTION_PATH}/src/runner/index.ts
      env:
        # Base-action inputs
        LETTA_CODE_ACTION: "1"
        INPUT_PROMPT_FILE: ${{ runner.temp }}/letta-prompts/letta-prompt.txt
        INPUT_LETTA_ARGS: ${{ steps.prepare.outputs.letta_args }}
        INPUT_ACTION_INPUTS_PRESENT: ${{ steps.prepare.outputs.action_inputs_present }}
        INPUT_PATH_TO_LETTA_EXECUTABLE: ${{ inputs.path_to_letta_executable }}
        INPUT_PATH_TO_BUN_EXECUTABLE: ${{ inputs.path_to_bun_executable }}
        INPUT_SHOW_FULL_OUTPUT: ${{ inputs.show_full_output }}
        INPUT_MODEL: ${{ inputs.model }}
        INPUT_AGENT_ID: ${{ steps.prepare.outputs.agent_id }}

        # GitHub configuration
        GITHUB_TOKEN: ${{ steps.prepare.outputs.GITHUB_TOKEN }}

        # Letta configuration
        LETTA_API_KEY: ${{ inputs.letta_api_key }}
        LETTA_BASE_URL: ${{ inputs.letta_base_url }}

        # Skill environment variables
        LETTA_COMMENT_ID: ${{ steps.prepare.outputs.letta_comment_id }}
        LETTA_AGENT_ID: ${{ steps.prepare.outputs.agent_id }}
        LETTA_MODEL: ${{ steps.letta-code.outputs.model || inputs.model }}
        LETTA_ADE_URL: https://app.letta.com/agents/${{ steps.prepare.outputs.agent_id }}
        BRANCH_NAME: ${{ steps.prepare.outputs.LETTA_BRANCH }}
        BASE_BRANCH: ${{ steps.prepare.outputs.BASE_BRANCH }}

    - name: Update comment with job link
      if: steps.prepare.outputs.contains_trigger == 'true' && steps.prepare.outputs.letta_comment_id && always()
      shell: bash
      run: |
        bun run ${GITHUB_ACTION_PATH}/src/entrypoints/update-comment-link.ts
      env:
        REPOSITORY: ${{ github.repository }}
        PR_NUMBER: ${{ github.event.issue.number || github.event.pull_request.number }}
        LETTA_COMMENT_ID: ${{ steps.prepare.outputs.letta_comment_id }}
        GITHUB_RUN_ID: ${{ github.run_id }}
        GITHUB_TOKEN: ${{ steps.prepare.outputs.GITHUB_TOKEN }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        TRIGGER_COMMENT_ID: ${{ github.event.comment.id }}
        LETTA_BRANCH: ${{ steps.prepare.outputs.LETTA_BRANCH }}
        IS_PR: ${{ github.event.issue.pull_request != null || github.event_name == 'pull_request_target' || github.event_name == 'pull_request_review_comment' }}
        BASE_BRANCH: ${{ steps.prepare.outputs.BASE_BRANCH }}
        LETTA_SUCCESS: ${{ steps.letta-code.outputs.conclusion == 'success' }}
        OUTPUT_FILE: ${{ steps.letta-code.outputs.execution_file || '' }}
        AGENT_ID: ${{ steps.letta-code.outputs.agent_id || '' }}
        LETTA_MODEL: ${{ steps.letta-code.outputs.model || inputs.model }}
        TRIGGER_USERNAME: ${{ github.event.comment.user.login || github.event.issue.user.login || github.event.pull_request.user.login || github.event.sender.login || github.triggering_actor || github.actor || '' }}
        PREPARE_SUCCESS: ${{ steps.prepare.outcome == 'success' }}
        PREPARE_ERROR: ${{ steps.prepare.outputs.prepare_error || '' }}
        USE_STICKY_COMMENT: ${{ inputs.use_sticky_comment }}
        USE_COMMIT_SIGNING: ${{ inputs.use_commit_signing }}
        TRACK_PROGRESS: ${{ inputs.track_progress }}

    - name: Display Letta Code Report
      if: steps.prepare.outputs.contains_trigger == 'true' && steps.letta-code.outputs.execution_file != ''
      shell: bash
      run: |
        # Try to format the output, but if it fails, dump the raw JSON
        if bun run ${{ github.action_path }}/src/entrypoints/format-turns.ts "${{ steps.letta-code.outputs.execution_file }}" >> $GITHUB_STEP_SUMMARY 2>/dev/null; then
          echo "Successfully formatted Letta Code report"
        else
          echo "## Letta Code Report (Raw Output)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Failed to format output (please report). Here's the raw JSON:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```json' >> $GITHUB_STEP_SUMMARY
          cat "${{ steps.letta-code.outputs.execution_file }}" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
        fi

    - name: Revoke app token
      if: always() && inputs.github_token == '' && steps.prepare.outputs.skipped_due_to_workflow_validation_mismatch != 'true'
      shell: bash
      run: |
        curl -L \
          -X DELETE \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ steps.prepare.outputs.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          ${GITHUB_API_URL:-https://api.github.com}/installation/token
